# Google OAuth properties
google-client-id=
google-client-secret=
firestore-scope=https://www.googleapis.com/auth/datastore
firestore-endpoint=https://firestore.googleapis.com/v1
firestore-database-id=sj-customer2
firestore-collection=sj-customer
secret-manager-scope=https://www.googleapis.com/auth/cloud-platform
secret-manager-endpoint=https://secretmanager.googleapis.com/v1
